name: Verify using Cosign

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed

env:
  REGISTRY: docker.cloudsmith.io
  IMAGE_NAME: jack-test-org/jack-test-repo/flask_app # OSS_DEMO_INPUTS: Update to {org_name}/{repo_name}/flask_app
  CERT_ID: https://github.com/jackgibson1/oss_secure_demo/.github/workflows/main.yml@refs/heads/main # OSS_DEMO_INPUTS: Update to GitHib username
  CERT_OIDC_ISSUER: https://token.actions.githubusercontent.com

jobs:
  verify-and-extract:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Install cosign
      uses: sigstore/cosign-installer@v3.5.0

    - name: Authenticate with Cloudsmith Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.CLOUDSMITH_USER_NAME }}
        password: ${{ secrets.CLOUDSMITH_API_KEY }}

    - name: Verify image
      run: |
        cosign verify \
          --certificate-identity  ${{ env.CERT_ID }} \
          --certificate-oidc-issuer ${{ env.CERT_OIDC_ISSUER }} \
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
